In [2]:
import numpy as np

In [3]:
# Creating one dimensional array
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
# Creating two dimensional array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [8]:
# Get dimensions of the array
arr.ndim

1

In [9]:
# Get shape of the array
arr.shape

(3,)

In [10]:
# Get data type
arr.dtype

dtype('int32')

In [11]:
# Get size
arr.itemsize

4

In [15]:
# Get total size
# arr.size * arr.itemsize
# Or
arr.nbytes

12

In [5]:
a = np.array([[1, 2, 3 , 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
# Getting little more customized output [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [7]:
# All zeros matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# All 1s matrix
np.ones((2, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
# Initializing matrix with any other value
np.full((2, 4), 16)

array([[16, 16, 16, 16],
       [16, 16, 16, 16]])

In [14]:
# Making matrix with any other value (When the matrix is already created)
np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [15]:
# Initializing matrix with random decimal numbers
np.random.rand(4, 2)

array([[0.26883734, 0.66766395],
       [0.85768233, 0.66281217],
       [0.93684278, 0.72192265],
       [0.63287101, 0.72607766]])

In [18]:
# # Initializing matrix with random decimal numbers
np.random.randint(8, size=(3,3))

array([[5, 6, 1],
       [4, 0, 2],
       [4, 1, 4]])

In [19]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Repeating the array
arr = np.array([[1, 2, 3]])
rep = np.repeat(arr, 3, axis=0)
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Assignment

In [33]:
# Printing the matrix using above concepts
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

output = np.ones((5, 5))
z = np.zeros((3, 3))
z[1, 1] = 9
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Very important concept

In [34]:
# Copying array
a = np.array([1, 2 ,3])
b = a.copy()
print(b)

[1 2 3]


## Mathematics

In [36]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [39]:
# Adding 2 to each element
arr + 2

array([3, 4, 5, 6, 7])

In [41]:
# Adding 2 to each element
arr += 2
print(arr)

[5 6 7 8 9]


In [44]:
# Adding two arrays
arr1 = np.array([1, 2 ,5, 3, 1])
arrAdd = arr + arr1
print(arrAdd)

[ 6  8 12 11 10]


In [46]:
# Taking square of each element in the array
a ** 2

array([1, 4, 9], dtype=int32)

In [47]:
# Taking cosine of each element in the array
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

## Linear Algebra

In [54]:
# Matrix multiplication of the matrices of different size
# No. of rows of one matrix must be equal to the no. of columns of the another matrix and vice versa
a = np.ones((2,3))
b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [57]:
# Finding the determinant
a = np.identity(3)
np.linalg.det(a)

1.0

## Statistics

In [61]:
# Finding the min from the array
stats = np.array([[1, 2, 3],[4, 5, 6]])
np.min(stats)

1

In [62]:
# Finding the max from the array
np.max(stats)

6

In [68]:
# Finding min from each row of the matrix
np.min(stats, axis = 1)

array([1, 4])

In [72]:
# Finding min from each column of the matrix
np.min(stats, axis = 0)

array([1, 2, 3])

In [71]:
# Finding max from each row of the matrix
np.max(stats, axis = 1)

array([3, 6])

In [73]:
# Finding min from each column of the matrix
np.max(stats, axis = 0)

array([4, 5, 6])

## Reorganizing arrays

In [76]:
# Reshaping the array
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(before)
after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [77]:
# Reshaping the array
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(before)
after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [79]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [81]:
# Horizontally stacking vectors
h1 = np.zeros((2, 4))
h2 = np.ones((2, 2))
np.hstack([h1, h2])

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

## Miscellaneous
### Load data from file

In [88]:
# Loading data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[1 2 6 4 5 2 3 8 7 5]
 [2 4 6 3 5 4 3 9 2 8]
 [1 6 3 5 4 8 9 6 5 4]]


## Boolean masking and Advanced indexing

In [90]:
# Boolean masking true if value is greater than 5
filedata > 5

array([[False, False,  True, False, False, False, False,  True,  True,
        False],
       [False, False,  True, False, False, False, False,  True, False,
         True],
       [False,  True, False, False, False,  True,  True,  True, False,
        False]])

In [92]:
# Getting all of the values greater than 5
filedata[filedata > 5]

array([6, 8, 7, 6, 9, 8, 6, 8, 9, 6])

In [93]:
# Checking the columns that have atleast one value greater than 5
np.any(filedata > 5, axis = 0)

array([False,  True,  True, False, False,  True,  True,  True,  True,
        True])

In [94]:
# Checking the columns that have all of the values greater than 5
np.all(filedata > 5, axis = 0)

array([False, False, False, False, False, False, False,  True, False,
       False])

In [95]:
# Getting all of the values greater than 5 and less than 7
((filedata > 5) & (filedata < 7))

array([[False, False,  True, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False,  True, False,
        False]])